### ISSUE TITLE
Moving builds over to bioconda

### ISSUE THREAD

**Issue by bgruening** [rdkit/conda-rdkit#13]
Hi,

is there any interest in moving these great recipes over to the bioconda channel? The bioconda community is trying hard to create sustainable packages that runs on most if not all distributions, including HPC. Moreover they have invested a lot of effort to test every PR and package before submitting automatically to anaconda.

https://github.com/bioconda/bioconda-recipes

Let me know what you think or if you have anything against me pushing these recopies also to bioconda.

Thanks,
Bjoern

**Comment by rvianello** [comment]
Hi @bgruening, sorry for the late reply.

I think this repository is likely to remain relevant to the rdkit project, and its development branch tends to follow more closely the evolution of the rdkit master branch, but the inclusion into bioconda of release packages based on the stable recipes from the conda-rdkit master could be interesting. @greglandrum what do you think?

A question for the bioconda team: what do you think about the recently announced conda-forge project (https://conda-forge.github.io/)? did you (or will you) consider moving (all or part of) the bioconda packages to it?

**Comment by bgruening** [comment]
@rvianello thanks for your answer.
You raise an interesting point. There are so many conda-recipes out there and it would be nice to join forces and offer one high quality recipe instead of multiple ones. For example I came to know about this one: https://github.com/omnia-md/conda-recipes
Which already has a nice rdkit recipe. So I think I will use this one. The big advantage is that it is compiled on a old cent-os so we can use the binaries nearly everywhere.

https://conda-forge.github.io is a nice project and I really hope we can move all to something like this and create on giant community to put everything together and not splitting up into sub-communities.

It would be nice if you could consider moving to one or the other projects. I will try to do the same :)
Thanks!

**Comment by greglandrum** [comment]
I'm even later to reply here. Sorry about that.
I'm super supportive of having RDKit conda builds available via bioconda, and would be fine suggesting that people use that instead of the rdkit channel on to install stable builds. conda-forge would, of course, be even better.

As @rvianello said: as developers of the RDKit itself, we are still going to need these recipes for our own uses.

**Comment by bgruening** [comment]
As a small update on this. We are still in progress of merging (depending on each other) bioconda and conda-forge.
As a side note here is a minimal Docker container of rdkit build with the conda recipe: https://github.com/mulled/mulled/pull/98

Will close this issue and try to update the bioconda recipe as much as I can.
