### ISSUE TITLE
consider porting to conda-forge?

### ISSUE THREAD

**Issue by pstjohn** [rdkit/conda-rdkit#44]
Have you considered hosting these recipes on [conda-forge](https://conda-forge.github.io)?
It might be a bit more automated/centralized than the anaconda-cloud option.

**Comment by greglandrum** [comment]
We've talked about it but never gotten around to seriously looking at it.

I suspect this repo would like need to remain intact anyway to allow the RDKit developers (and some of the more demanding users) to have control over builds, but investigating doing a conda-forge recipe is a really good idea.

**Comment by pstjohn** [comment]
I suppose 'porting' was the wrong word: I can definitely see where keeping these intact would be valuable. I've put together a few conda-forge recipes before, if I get a chance I'll look into how the `rdkit` recipe builds with their linux image and existing feedstocks.
