### ISSUE TITLE
Conda package rdkit-postgresql downgrades my rdkit conda package

### ISSUE THREAD

**Issue by malteseunderdog** [rdkit/conda-rdkit#77]
**I try to install the postgresql cartridge via conda install rdkit-postgresql but this does not work with the latest version of RDKit 2019.03.3**

It either installs 2018 version if run with 

```
conda create -c rdkit -n rdkit2 rdkit rdkit-postgresql
```

Or if I try -- I get a ton of dependency errors 

```
conda install -c rdkit -n rdkit rdkit-postgresql
```
  - rdkit/linux-64::rdkit==2019.03.3.0=py37hc20afe1_1 -> numpy[version='>=1.12'] -> mkl_fft[version='>=1.0.6,<2.0a0'] -> python[version='>=2.7,<2.8.0a0'] -> readline[version='>=7.0,<8.0a0']
  - rdkit/linux-64::rdkit==2019.03.3.0=py37hc20afe1_1 -> numpy[version='>=1.12'] -> mkl_fft[version='>=1.0.6,<2.0a0'] -> python[version='>=2.7,<2.8.0a0'] -> sqlite[version='>=3.27.2,<4.0a0'] -> libedit[version='>=3.1.20181209,<3.2.0a0']
  - rdkit/linux-64::rdkit==2019.03.3.0=py37hc20afe1_1 -> numpy[version='>=1.12'] -> mkl_fft[version='>=1.0.6,<2.0a0'] -> python[version='>=2.7,<2.8.0a0'] -> tk[version='>=8.6.8,<8.7.0a0']
  - rdkit/linux-64::rdkit==2019.03.3.0=py37hc20afe1_1 -> numpy[version='>=1.12'] -> mkl_random[version='>=1.0.2,<2.0a0']
  - rdkit/linux-64::rdkit==2019.03.3.0=py37hc20afe1_1 -> pandas
  - rdkit/linux-64::rdkit==2019.03.3.0=py37hc20afe1_1 -> pillow -> jpeg[version='>=9b,<10a']
  - rdkit/linux-64::rdkit==2019.03.3.0=py37hc20afe1_1 -> pillow -> libtiff[version='>=4.0.10,<5.0a0'] -> zstd[version='>=1.3.7,<1.3.8.0a0']
  - rdkit/linux-64::rdkit==2019.03.3.0=py37hc20afe1_1 -> pillow -> olefile
  - rdkit/linux-64::rdkit==2019.03.3.0=py37hc20afe1_1 -> py-boost

- RDKit Version: 2019.03.3
- Platform: Ubuntu 18.04

**Comment by greglandrum** [comment]
I didn't manage to finish doing the cartridge build when I did the python builds.
I'll try and get it up later today.

In the meantime: It is a generally good idea anyway to have separate conda envs for these things.
