### ISSUE TITLE
Default rdkit from conda uses outdated version

### ISSUE THREAD

**Issue by vfscalfani** [rdkit/conda-rdkit#84]
Hello,

Installing rdkit via conda on Ubuntu 18.04 as follows:

`conda create -c rdkit -n my-rdkit-env rdkit`

tries to install an older version for me: rdkit-2017.09.1

However, the following works fine for getting the latest:
`conda create -c rdkit -n my-rdkit-env rdkit=2019.09.2`

Thanks
Vin

**Comment by hsiaoyi0504** [comment]
`conda install -c rdkit rdkit=2020.03.2` works for me.

**Comment by UnixJunkie** [comment]
It would be nice if the latest released version is installed automatically.

**Comment by gfrogat** [comment]
I opened a similar issue in the main RDKit repo https://github.com/rdkit/rdkit/issues/3062 

It seems the RDKit version also sometimes depends on the Python version that is used for the environment.

**Comment by bdelepine** [comment]
As @gfrogat showed in rdkit/rdkit#3062, it seems that the `rdkit` channel is not up to date but that `conda-forge` is. Consequently, `conda create -c conda-forge -n my-rdkit-env rdkit` should give latest version.

And I confirm that rdkit version depends on python's version installed via `rdkit` channel. On my tests, I had:

* `conda create -c rdkit -n test rdkit` ==> rdkit/linux-64::rdkit-2018.03.2.0-py36h6bb024c_1
* `conda create -c rdkit -n test python=3.6 rdkit` ==> rdkit/linux-64::rdkit-2018.03.2.0-py36h6bb024c_1
* `conda create -c rdkit -n test python=3.7 rdkit` ==> rdkit/linux-64::rdkit-2020.03.3.0-py37hc20afe1_1
* `conda create -c rdkit -n test python=3.8 rdkit` ==> UnsatisfiableError
* all my test with conda-forge used conda-forge/linux-64::rdkit-2020.03.6-*

More on the UnsatisfiableError:
```bash
conda create -c rdkit -n test2 python=3.8 rdkit
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
rdkit -> numpy[version='>=1.12'] -> python[version='>=3.8,<3.9.0a0']
python=3.8
rdkit -> python[version='2.6.*|2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|3.4.*']

**Comment by antoson** [comment]
Installing from conda-forge channel gets the latest version (2020.09.5) `conda install -c conda-forge rdkit `.
I was really surprised that `conda create -c rdkit -n my-rdkit-env rdkit` from [official docs](https://www.rdkit.org/docs/Install.html) doesn't install latest version 🤔.

**Comment by vfscalfani** [comment]
@antoson oh, actually, the docs were just updated today to use the conda-forge channel: https://www.rdkit.org/docs/Install.html. See also the latest email from Greg: https://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg10517.html

**Comment by pbjarterot** [comment]
for me it worked with :

`conda install -c conda-forge rdkit=2021.09.1 `

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
